# serverless.yml (excerpt)

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  # ... other provider settings ...
  iam:
    role:
      statements:
        # Standard logging permissions (keep these)
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 'arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/*:*:*'
        # --- ADD/UPDATE THIS SECTION FOR SECRETS MANAGER PERMISSIONS ---
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          # This resource ARN specifically allows access to your secret.
          # The `*-` at the end is a common pattern to match different versions of the secret.
          Resource: 'arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:dev_transactions_secret-*'
        # ----------------------------------------------------------------
        # Add kms:Decrypt if you are using a custom KMS key for the secret
        # (if you used the default `aws/secretsmanager` key, it's usually not needed explicitly here)
        # - Effect: Allow
        #   Action:
        #     - kms:Decrypt
        #   Resource: '*' # Be specific if you use a custom KMS key ARN

functions:
  # ... your functions ...
