# serverless.yml
service: lambda-api # Or whatever your service name is

frameworkVersion: "4" # Ensure this is present for Serverless Framework v4

provider:
  name: aws
  runtime: python3.9
  region: us-east-1 # Ensure this matches your AWS_REGION
  stage: ${opt:stage, 'dev'}
  # ... other provider settings like environment variables, IAM roles etc.

plugins:
  - serverless-python-requirements # ADD THIS LINE IF NOT PRESENT

custom:
  pythonRequirements:
    dockerizePip: true # Recommended for complex dependencies or non-Linux local dev
    # Add other configurations as needed, e.g.:
    # slim: true
    # noDeploy:
    #   - docutils
    #   - pylint
    #   - boto3
    #   - botocore
    #   - jmespath
    #   - s3transfer

functions:
  hello:
    handler: handler.hello # Assuming your handler is in handler.py
    # ... other function settings
    events:
      - httpApi:
          path: /hello
          method: GET

# You might have other resources or configurations here
