# serverless.yml

service: power-transactions

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 128
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 'arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/*:*:*'
        
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: 'arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:dev_transactions_secret-*'
        
        # If your KMS key for the secret isn't the default 'aws/secretsmanager',
        # you might also need kms:Decrypt permissions. Uncomment and specify ARN if necessary.
        # - Effect: Allow
        #   Action:
        #     - kms:Decrypt
        #   Resource: 'arn:aws:kms:${aws:region}:${aws:accountId}:key/<your-kms-key-id>'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  main:
    name: power-transactions
    handler: lambda_function.lambda_handler
    
    events:
      # --- ENABLED SCHEDULED EVENTS (ALL UTC) ---
      - schedule:
          rate: cron(0 0 * * ? *) # Runs at 12:00 AM UTC (midnight)
          enabled: true
          input:
            summary_type: "midnight_summary" 
      - schedule:
          rate: cron(0 6 * * ? *) # Runs at 6:00 AM UTC
          enabled: true
          input:
            summary_type: "morning_summary" # Changed input type for clarity
      - schedule:
          rate: cron(0 12 * * ? *) # Runs at 12:00 PM UTC (noon)
          enabled: true
          input:
            summary_type: "midday_summary" # Changed input type for clarity
      - schedule:
          rate: cron(0 18 * * ? *) # Runs at 6:00 PM UTC
          enabled: true
          input:
            summary_type: "evening_summary" # Changed input type for clarity
      # --- END ENABLED SCHEDULED EVENTS ---
      
      # Keep HTTP API endpoint commented unless you need it:
      # - httpApi:
      #     path: /transactions/summary
      #     method: GET
