# serverless.yml

service: power-transactions

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 128
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 'arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/*:*:*'
        
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: 'arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:dev_transactions_secret-*'
        
        # If your KMS key for the secret is not the default 'aws/secretsmanager',
        # you might also need kms:Decrypt permissions. Uncomment and specify ARN if necessary.
        # - Effect: Allow
        #   Action:
        #     - kms:Decrypt
        #   Resource: 'arn:aws:kms:${aws:region}:${aws:accountId}:key/<your-kms-key-id>'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  main:
    name: power-transactions
    handler: lambda_function.lambda_handler
    
    # Define events that trigger this Lambda function (e.g., schedules, HTTP API, SQS, etc.)
    events:
      # --- ENABLED SCHEDULED EVENTS ---
      - schedule:
          rate: cron(0 0 * * ? *) # This runs at 12:00 AM UTC (midnight)
          enabled: true
          input:
            summary_type: "midnight_summary" # You can customize this input type
      - schedule:
          rate: cron(0 5 * * ? *) # This runs at 5:00 AM UTC
          enabled: true
          input:
            summary_type: "daily_6am_wat"
      - schedule:
          rate: cron(0 11 * * ? *) # This runs at 11:00 AM UTC
          enabled: true
          input:
            summary_type: "midday_12pm_wat"
      - schedule:
          rate: cron(0 17 * * ? *) # This runs at 5:00 PM UTC
          enabled: true
          input:
            summary_type: "evening_6pm_wat"
      # --- END ENABLED SCHEDULED EVENTS ---
      
      # If you have an HTTP API endpoint, keep it here uncommented:
      # - httpApi:
      #     path: /transactions/summary
      #     method: GET
