# serverless.yml

service: power-transactions

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  timeout: 30
  memorySize: 128
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 'arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/*:*:*'
        
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: 'arn:aws:secretsmanager:${aws:region}:${aws:accountId}:secret:dev_transactions_secret-*'
        
        # If your KMS key for the secret isn't the default 'aws/secretsmanager',
        # you might also need kms:Decrypt permissions. Uncomment and specify ARN if necessary.
        # - Effect: Allow
        #   Action:
        #     - kms:Decrypt
        #   Resource: 'arn:aws:kms:${aws:region}:${aws:accountId}:key/<your-kms-key-id>'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  main:
    name: power-transactions
    handler: lambda_function.lambda_handler
    
    events:
      # --- SCHEDULED EVENTS - CONFIGURED FOR WEST AFRICAN TIME (WAT - UTC+1) ---
      - schedule:
          rate: cron(0 23 * * ? *) # Triggers at 12:00 AM WAT (which is 11:00 PM UTC of the previous day)
          enabled: true
          input:
            summary_type: "midnight_wat_summary"
      - schedule:
          rate: cron(0 5 * * ? *) # Triggers at 6:00 AM WAT (which is 5:00 AM UTC)
          enabled: true
          input:
            summary_type: "morning_wat_summary" 
      - schedule:
          rate: cron(0 11 * * ? *) # Triggers at 12:00 PM WAT (which is 11:00 AM UTC)
          enabled: true
          input:
            summary_type: "midday_wat_summary" 
      - schedule:
          rate: cron(0 17 * * ? *) # Triggers at 6:00 PM WAT (which is 5:00 PM UTC)
          enabled: true
          input:
            summary_type: "evening_wat_summary" 
      # --- END SCHEDULED EVENTS ---
      
      # Keep HTTP API endpoint commented unless you need it:
      # - httpApi:
      #     path: /transactions/summary
      #     method: GET
