# serverless.yml
service: dev_transactions # You can set your service name here. Using 'dev_transactions' for clarity.

frameworkVersion: "4" # Ensure this is present for Serverless Framework v4

provider:
  name: aws
  runtime: python3.10 # <--- MODIFIED: Set runtime to Python 3.10 as per your screenshot
  region: us-east-1 # Ensure this matches your AWS_REGION
  stage: ${opt:stage, 'dev'}
  # ... other provider settings like environment variables, IAM roles etc.

plugins:
  - serverless-python-requirements # Ensure this is still listed

custom:
  pythonRequirements:
    dockerizePip: true
    # Add other configurations as needed

functions:
  # Define your function here. The key 'yourFunctionName' is an internal reference.
  main: # <--- You can name this function key anything, e.g., 'main' or 'myHandler'
    name: dev_transactions # <--- CRITICAL CHANGE: Explicitly sets the deployed AWS Lambda function name to 'dev_transactions'
    handler: lambda_function.lambda_handler # <--- MODIFIED: Set handler as per your screenshot
    events:
      # If your 'dev_transactions' function uses API Gateway, define its events here.
      # Example (adjust path as needed):
      # - httpApi:
      #     path: /api/transactions
      #     method: ANY
      # - httpApi:
      #     path: /api/transactions/{proxy+}
      #     method: ANY

# You might have other resources or configurations here
