# serverless.yml
# The 'service' name must use hyphens, not underscores, for CloudFormation compatibility.
# This will form the base of your CloudFormation stack name (e.g., power-transactions-prod)
service: power-transactions # <--- MODIFIED: Changed service name to use hyphens

frameworkVersion: "4"

provider:
  name: aws
  runtime: python3.10 # Keeping Python 3.10 as per your previous function
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  # ... other provider settings like environment variables, IAM roles etc.

plugins:
  - serverless-python-requirements # Ensure this is still listed

custom:
  pythonRequirements:
    dockerizePip: true
    # Add other configurations as needed

functions:
  # 'main' is the internal function key for this function definition.
  # The 'name' property below will override the default AWS Lambda function name.
  main:
    name: power-transactions # <--- CRITICAL CHANGE: Explicitly sets the deployed AWS Lambda function name
    handler: lambda_function.lambda_handler # <--- Keeping your handler path
    events:
      # If your 'power-transactions' function uses API Gateway, define its events here.
      # Example:
      # - httpApi:
      #     path: /api/power
      #     method: ANY
      # - httpApi:
      #     path: /api/power/{proxy+}
      #     method: ANY

# You might have other resources or configurations here
