#boss
# .github/workflows/deploy.yml
name: Deploy Serverless App

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Serverless Framework CLI
        run: npm install -g serverless

      # --- ADD THIS NEW STEP HERE ---
      - name: Install Serverless Python Requirements Plugin
        run: npm install --save-dev serverless-python-requirements
      # ----------------------------

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Lambda dependencies
        run: |
          pip install -r requirements.txt

      - name: Serverless Deploy to Development Environment
        if: github.ref == 'refs/heads/develop'
        env:
          SERVERLESS_LICENSE_KEY: ${{ secrets.SERVERLESS_LICENSE_KEY }}
        run: |
          serverless deploy --stage dev --verbose

      - name: Serverless Deploy to Production Environment
        if: github.ref == 'refs/heads/main'
        env:
          SERVERLESS_LICENSE_KEY: ${{ secrets.SERVERLESS_LICENSE_KEY }}
        run: |
          serverless deploy --stage prod --verbose
