# .github/workflows/deploy.yml
name: Deploy Serverless App

on:
  push:
    branches:
      - main # Triggers on push to main branch (for prod deployment)
      - develop # Triggers on push to develop branch (for dev deployment)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1 # <<< IMPORTANT: Set your AWS Region here to US East (N. Virginia)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python # CHANGED: From Node.js to Python
        uses: actions/setup-python@v5 # CHANGED: Action for Python
        with:
          python-version: '3.9' # CHANGED: Specify your Python runtime version

      - name: Install Serverless Framework CLI
        run: npm install -g serverless

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Lambda dependencies
        run: |
          # For Python: install requirements (serverless-python-requirements plugin handles packaging)
          pip install -r requirements.txt # UNCOMMENTED for Python
          # For Node.js: install node modules
          # npm install # COMMENTED OUT for Python
        working-directory: my-serverless_deployment # UPDATED: Use your actual project folder name

      - name: Serverless Deploy to Development Environment
        if: github.ref == 'refs/heads/develop' # Only run for 'develop' branch
        run: |
          serverless deploy --stage dev --verbose # --verbose for more detailed output

      - name: Serverless Deploy to Production Environment
        if: github.ref == 'refs/heads/main' # Only run for 'main' branch
        run: |
          serverless deploy --stage prod --verbose # --verbose for more detailed output
